defaults:
  - _self_
  - base_entities

_target_: vivarium.environment.components.entities.objects.ObjectComponent
precedence: 10
n_max: 4
mass:
  _all_values_: 1.0
diameter:
  _all_values_: 8.0
friction:
  _all_values_: 1.0
