# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import simulator_pb2 as simulator__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in simulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulatorServerStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Step = channel.unary_unary(
                '/simulator.SimulatorServer/Step',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.SetChangesAndStep = channel.unary_unary(
                '/simulator.SimulatorServer/SetChangesAndStep',
                request_serializer=simulator__pb2.StateChangeList.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/simulator.SimulatorServer/GetState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.GetControllerParameters = channel.unary_unary(
                '/simulator.SimulatorServer/GetControllerParameters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.GetStateAndControllerParameters = channel.unary_unary(
                '/simulator.SimulatorServer/GetStateAndControllerParameters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.SetChangesReturnsState = channel.unary_unary(
                '/simulator.SimulatorServer/SetChangesReturnsState',
                request_serializer=simulator__pb2.StateChangeList.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.SetChanges = channel.unary_unary(
                '/simulator.SimulatorServer/SetChanges',
                request_serializer=simulator__pb2.StateChangeList.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetSceneName = channel.unary_unary(
                '/simulator.SimulatorServer/GetSceneName',
                request_serializer=simulator__pb2.Scene.SerializeToString,
                response_deserializer=simulator__pb2.Scene.FromString,
                _registered_method=True)
        self.RegisterClient = channel.unary_unary(
                '/simulator.SimulatorServer/RegisterClient',
                request_serializer=simulator__pb2.Client.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UnregisterClient = channel.unary_unary(
                '/simulator.SimulatorServer/UnregisterClient',
                request_serializer=simulator__pb2.Client.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.IsRunning = channel.unary_unary(
                '/simulator.SimulatorServer/IsRunning',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=simulator__pb2.IsRunningState.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/simulator.SimulatorServer/Start',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/simulator.SimulatorServer/Stop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/simulator.SimulatorServer/StreamState',
                request_serializer=simulator__pb2.StreamConfig.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)
        self.BidirectionalStep = channel.stream_stream(
                '/simulator.SimulatorServer/BidirectionalStep',
                request_serializer=simulator__pb2.StateChangeList.SerializeToString,
                response_deserializer=simulator__pb2.Dataclass.FromString,
                _registered_method=True)


class SimulatorServerServicer(object):
    """Interface exported by the server.
    """

    def Step(self, request, context):
        """Do a step in the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChangesAndStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Get state of the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControllerParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateAndControllerParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChangesReturnsState(self, request, context):
        """send changes made on the client side to the simulator server (returns updated state)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetChanges(self, request, context):
        """send changes without returning state (for use with streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSceneName(self, request, context):
        """send the labels of subtypes and scene name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsRunning(self, request, context):
        """Handle the connection between the server and the clients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """============ Streaming RPCs ============

        Server-side streaming: Subscribe to state updates when server is running
        Server pushes state whenever it changes (after each step)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStep(self, request_iterator, context):
        """Bidirectional streaming: Send commands, receive state updates
        Client sends changes, server responds with updated state after each step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'SetChangesAndStep': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChangesAndStep,
                    request_deserializer=simulator__pb2.StateChangeList.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'GetControllerParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllerParameters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'GetStateAndControllerParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateAndControllerParameters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'SetChangesReturnsState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChangesReturnsState,
                    request_deserializer=simulator__pb2.StateChangeList.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'SetChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.SetChanges,
                    request_deserializer=simulator__pb2.StateChangeList.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetSceneName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSceneName,
                    request_deserializer=simulator__pb2.Scene.FromString,
                    response_serializer=simulator__pb2.Scene.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=simulator__pb2.Client.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UnregisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterClient,
                    request_deserializer=simulator__pb2.Client.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'IsRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.IsRunning,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=simulator__pb2.IsRunningState.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=simulator__pb2.StreamConfig.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
            'BidirectionalStep': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStep,
                    request_deserializer=simulator__pb2.StateChangeList.FromString,
                    response_serializer=simulator__pb2.Dataclass.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulator.SimulatorServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulator.SimulatorServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulatorServer(object):
    """Interface exported by the server.
    """

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/Step',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetChangesAndStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/SetChangesAndStep',
            simulator__pb2.StateChangeList.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/GetState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControllerParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/GetControllerParameters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStateAndControllerParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/GetStateAndControllerParameters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetChangesReturnsState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/SetChangesReturnsState',
            simulator__pb2.StateChangeList.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/SetChanges',
            simulator__pb2.StateChangeList.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSceneName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/GetSceneName',
            simulator__pb2.Scene.SerializeToString,
            simulator__pb2.Scene.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/RegisterClient',
            simulator__pb2.Client.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/UnregisterClient',
            simulator__pb2.Client.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/IsRunning',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            simulator__pb2.IsRunningState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/Start',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.SimulatorServer/Stop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/simulator.SimulatorServer/StreamState',
            simulator__pb2.StreamConfig.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BidirectionalStep(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/simulator.SimulatorServer/BidirectionalStep',
            simulator__pb2.StateChangeList.SerializeToString,
            simulator__pb2.Dataclass.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
