syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.simulator";
option java_outer_classname = "SimulatorProto";
option objc_class_prefix = "SIM";

import "google/protobuf/empty.proto";
package simulator;

// Interface exported by the server.
service SimulatorServer {
  // Do a step in the simulation
  rpc Step(google.protobuf.Empty) returns (Dataclass) {}
  rpc SetChangesAndStep(StateChangeList) returns (Dataclass) {}
  
  // Get state of the simulation
  rpc GetState(google.protobuf.Empty) returns (Dataclass) {}
  rpc GetSimulatorParameters(google.protobuf.Empty) returns (Dataclass) {}

  rpc SetControllerAtrributes(Dataclass) returns (google.protobuf.Empty) {}

  // send changes made on the client side to the simulator server
  rpc SetChanges(StateChangeList) returns (google.protobuf.Empty) {}

  // send the labels of subtypes and scene name
  rpc GetSceneName(Scene) returns (Scene) {}

  // Handle the connection between the server and the clients
  rpc IsStarted(google.protobuf.Empty) returns (IsStartedState) {}
  rpc Start(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc Stop(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message Dataclass {
  Value value = 1;  // For numpy arrays
  map<string, Dataclass> nested_fields = 2;  // For nested dataclasses
}

message Slice {
  optional int32 start = 1;
  optional int32 stop = 2;
  optional int32 step = 3;
}

message Idx {
  oneof idx {
    int32 int_idx = 1;
    Slice slice_idx = 2;
    bool is_none = 3;
  }
}

message Indexes {
  repeated Idx idx = 1;
}

message Index {
  oneof index {
    Idx idx = 1;
    Indexes indexes = 2;
  }
}

message Value {
  oneof value {
    NDArray ndarray = 1;
    bool bool_value = 3;
    int32 int_value = 4;
    float float_value = 5;
    string str_value = 6;
    List list_value = 7;
  }
}

message List {
  repeated float list = 1;
}

message Change {
  Index idx = 1;
  Value value = 2;
}

message Changes {
  repeated Change changes = 1;
}

message StateChange {
  Changes changes = 1;
  map<string, StateChange> child = 2;
}

message StateChangeList {
  repeated StateChange state_changes = 1;
}

message NDArray {
  bytes ndarray = 1;
}

message RigidBody {
  NDArray center = 1;
  NDArray orientation = 2;
}

message IsStartedState {
  bool is_started = 1;
}

message Scene {
  string scene_name = 1;
}