environment:
  cls: vivarium.environments.Environment
  kwargs:
    box_size: 100.0
    neighbor_radius: 300.0
    num_scan_steps: 100
    to_jit: True
  state_fns:
    # _target_: builtins.dict
    reset:
      _target_: vivarium.environments.physics_engine.ResetForce
      precedence: 0
    proximity_map:
      _target_: vivarium.environments.physics_engine.ProximityMap
      precedence: 1
    collision:
      _target_: vivarium.environments.physics_engine.CollisionForce
      precedence: 2
      epsilon: 1.0
      alpha: 2.0
      mask_fn:
        _target_: vivarium.environments.environment.get_mask_fn
        label: exists
    friction:
      _target_: vivarium.environments.physics_engine.FrictionForce
      precedence: 3
      mask_fn:
        _target_: vivarium.environments.environment.get_mask_fn
        label: exists
    spawn_resources:
      _target_: vivarium.environments.dynamics.existence.SpawnDynamics
      precedence: 4
      subtype: 2
      period: 1000
      position_range: [0, 100, 0, 100]
      orientation_range: [0, 0.0001]
    # spawn_preys:
    #   _target_: vivarium.environments.dynamics.existence.SpawnDynamics
    #   precedence: 3
    #   subtype: 0
    #   period: 1000
    #   position_range: [0, 100, 0, 100]
    #   orientation_range: [0, 6.28]
    preys_consume_resources:
      _target_: vivarium.environments.dynamics.existence.ConsumptionDynamics
      precedence: 5
      source_subtype: 0
      target_subtype: 2
      range: 10.0
    energy_preys:
      _target_: vivarium.environments.dynamics.existence.EnergyDynamics
      precedence: 6
    predators_consume_preys:
      _target_: vivarium.environments.dynamics.existence.ConsumptionDynamics
      precedence: 7
      source_subtype: 1
      target_subtype: 0
      range: 10.0
    energy_predators:
      _target_: vivarium.environments.dynamics.existence.EnergyDynamics
      precedence: 8
    reproduction:
      _target_: vivarium.environments.dynamics.existence.ReproductionDynamics
      precedence: 9
    braitenberg:
      _target_: vivarium.environments.entities.braitenberg.BraitenbergDynamics
      precedence: 10
      entity_type: agents
    step:
      _target_: vivarium.environments.physics_engine.Step
      precedence: 1000
      mask_fn:
        _target_: vivarium.environments.environment.get_mask_fn
        label: exists

simulator:
  cls: vivarium.simulator.Simulator
  kwargs:
    freq: 40

subtypes:
  - prey
  - predator
  - resource

state:
  cls: vivarium.environments.state.BaseState
  kwargs:
    time: 0
    dt: 0.1
    # collision_alpha: 2.0
    # collision_eps: 1.0

entities:
  entity_state:
    cls: vivarium.environments.state.EntityState
  entity_types:
    - agents
    - objects

  agents:
    cls: vivarium.environments.entities.braitenberg.AgentState
    simulator_controller_cls: vivarium.controllers.simulator_controller.ControllerAgent
    kwargs:
      n_exists: 24
      mass:
        _all_values_: 1.0
      position: random
      orientation: random
      diameter:
        _all_values_: 6.0
      friction:
        _all_values_: 1.0
      n_behaviors: 4
      subtype_to_n:
        - [0, 12]
        - [1, 12]
      wheel_diameter:
        _all_values_: 3.0
      proxs_dist_max:
        _all_values_: 20.0
      proxs_cos_min:
        _all_values_: 0.0

  objects:
    cls: vivarium.environments.entities.objects.ObjectState
    simulator_controller_cls: vivarium.controllers.simulator_controller.ControllerObject
    kwargs:
      n_max: 60
      n_exists: 60
      mass:
        _all_values_: 1.0
      position: random
      orientation:
        _all_values_: 0.0
      diameter:
        _all_values_: 3.0
      friction:
        _all_values_: 1.0
      subtype_to_n:
        - [2, 60]

client:
  agents:
    kwargs:
      color:
        _all_values_: red
      visible:
        _all_values_: true
      visible_wheels:
        _all_values_: true
      visible_proxs:
        _all_values_: true
    simulator_controller:
      cls: vivarium.controllers.simulator_controller.ControllerAgent
      kwargs: {}  #TODO: kwargs now defined a level upper, could be all removed at this level? (also in objects)
    notebook_controller:
      cls: vivarium.controllers.notebook_controller.Agent
      kwargs: {}
    param:
      cls: vivarium.controllers.panel_controller.Agent
      kwargs: {}
    panel_controller:
      cls: vivarium.controllers.panel_controller.PanelControllerAgent
      kwargs: {}
    panel_interface:
      cls: vivarium.interface.panel_app.AgentManager
      kwargs: {}
  objects:
    kwargs:
      color:
        _all_values_: blue
      visible:
        _all_values_: true
    simulator_controller:
      cls: vivarium.controllers.simulator_controller.ControllerObject
      kwargs: {}
    notebook_controller:
      cls: vivarium.controllers.notebook_controller.Object
      kwargs: {}
    param:
      cls: vivarium.controllers.panel_controller.Object
      kwargs: {}
    panel_controller:
      cls: vivarium.controllers.panel_controller.PanelControllerObject
      kwargs: {}
    panel_interface:
      cls: vivarium.interface.panel_app.ObjectManager
      kwargs: {}
